spring:
  datasource:
    url: jdbc:mysql://fuf-server.mysql.database.azure.com:3306/fuf?useSSL=true
    username: aga
    password: Fufadmin!1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080