INSERT INTO fuf.interest (id, emoji, title) VALUES (1, '?', 'IT');
INSERT INTO fuf.interest (id, emoji, title) VALUES (2, '?', 'beer');
INSERT INTO fuf.interest (id, emoji, title) VALUES (3, '?', 'BUFET');
INSERT INTO fuf.interest (id, emoji, title) VALUES (4, '??', 'Ukraine');
INSERT INTO fuf.interest (id, emoji, title) VALUES (5, '?', 'trumpets');
INSERT INTO fuf.interest (id, emoji, title) VALUES (6, '?', 'professional procrastinator');
INSERT INTO fuf.interest (id, emoji, title) VALUES (7, '?', 'reading');
INSERT INTO fuf.interest (id, emoji, title) VALUES (8, '?', 'cycling');
INSERT INTO fuf.interest (id, emoji, title) VALUES (9, '?', 'PlayStation');
INSERT INTO fuf.interest (id, emoji, title) VALUES (10, '?', 'clowns');
INSERT INTO fuf.interest (id, emoji, title) VALUES (11, '?', 'aliens');
INSERT INTO fuf.interest (id, emoji, title) VALUES (12, '?', 'ghosts');
INSERT INTO fuf.interest (id, emoji, title) VALUES (13, '?', 'retro games');
INSERT INTO fuf.interest (id, emoji, title) VALUES (14, '?', 'dogs');
INSERT INTO fuf.interest (id, emoji, title) VALUES (15, '?', 'cats');
INSERT INTO fuf.interest (id, emoji, title) VALUES (16, '?', 'horses');
INSERT INTO fuf.interest (id, emoji, title) VALUES (17, '?', 'toads');
INSERT INTO fuf.interest (id, emoji, title) VALUES (18, '?', 'rockets');
INSERT INTO fuf.interest (id, emoji, title) VALUES (19, '?', 'robots');
INSERT INTO fuf.interest (id, emoji, title) VALUES (20, '?', 'handcraft');
INSERT INTO fuf.interest (id, emoji, title) VALUES (21, '?', 'attractions');
INSERT INTO fuf.interest (id, emoji, title) VALUES (22, '✉', 'correspondence');
INSERT INTO fuf.interest (id, emoji, title) VALUES (23, '?', 'cryptocurrency');
INSERT INTO fuf.interest (id, emoji, title) VALUES (24, '?', 'barbershop');
INSERT INTO fuf.interest (id, emoji, title) VALUES (25, '?', 'skateboarding');
INSERT INTO fuf.interest (id, emoji, title) VALUES (26, '?', 'cars');
INSERT INTO fuf.interest (id, emoji, title) VALUES (27, '?', 'guitars');
INSERT INTO fuf.interest (id, emoji, title) VALUES (28, '?', 'shoping');
